2021-04-27 01:06:17,423 - loggingerror - ERROR - FATAL:  database "tabledata" does not exist
Traceback (most recent call last):
  File "E:\pythonflaskapiexample\crudoperations.py", line 92, in selectdatabytype
    conn = psycopg2.connect(dbname=databasename, user=username, host=hostname, password=password, port=portname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "tabledata" does not exist

2021-04-27 01:07:00,761 - loggingerror - ERROR - FATAL:  database "tabledata" does not exist
Traceback (most recent call last):
  File "E:\pythonflaskapiexample\crudoperations.py", line 92, in selectdatabytype
    conn = psycopg2.connect(dbname=databasename, user=username, host=hostname, password=password, port=portname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "tabledata" does not exist

2021-04-27 01:30:17,984 - loggingerror - ERROR - 0
Traceback (most recent call last):
  File "E:\pythonflaskapiexample\crudoperations.py", line 28, in insertintotable
    d = data[i]
KeyError: 0
